import fs from 'node:fs';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import worker from './dist/server/index.js';
const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))db.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const blobs=new Map(),env={DB:{prepare:sql=>({bind:(...v)=>({first:async()=>db.prepare(sql).get(...v)||null,all:async()=>({results:db.prepare(sql).all(...v)}),run:async()=>({meta:{changes:db.prepare(sql).run(...v).changes}})})})},BUCKET:{put:async(k,b,o)=>blobs.set(k,{body:b,httpMetadata:o.httpMetadata,arrayBuffer:async()=>new Uint8Array(b).buffer}),get:async k=>blobs.get(k),delete:async k=>blobs.delete(k)}};
let checks=0;function check(v,label){assert.ok(v,label);checks++}const origin='https://test.invalid';
async function request(path,{user='A',body,headers={},method}={}){const h={...headers};if(user){h['oai-authenticated-user-id']=user;h['oai-authenticated-user-email']=user+'@example.invalid'}if(body){h.origin??=origin;if(!(body instanceof FormData))h['content-type']='application/json'}const r=await worker.fetch(new Request(origin+'/api/'+path,{method:method||(body?'POST':'GET'),headers:h,body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined}),env);return {status:r.status,headers:r.headers,data:r.headers.get('content-type')?.includes('json')?await r.json():new Uint8Array(await r.arrayBuffer())}}
await request('profile',{body:{name:'Alice'}});await request('profile',{body:{name:'Bruno'},user:'B'});const alice=(await request('me')).data.id,bruno=(await request('me',{user:'B'})).data.id;
const id=crypto.randomUUID(),post={id,text:'Prova isolata',city:'Roma',kind:'Pioggia'};await request('posts',{body:post});
let r=await request('network/feed',{user:null});check(r.data.posts.length===1,'public feed reads shared posts');check(!JSON.stringify(r.data).includes('@'),'feed never discloses email');
await request('link',{user:'B',body:{kind:'follow',target:alice,active:true}});check((await request('network/feed?mode=following',{user:'B'})).data.posts.length===1,'following filter');check((await request('network/feed?mode=following',{user:null})).data.posts.length===0,'anonymous following is empty');
await request('link',{body:{kind:'save',target:id,active:true}});check((await request('network/feed?mode=saved')).data.posts.length===1,'saved filter');check((await request('network/feed?mode=local&city=roma')).data.posts.length===1,'city filter case insensitive');check((await request('network/feed?city=Tokyo')).data.posts.length===0,'different city excluded');check((await request('network/feed?q=inesistente')).data.posts.length===0,'text search filters');
r=await request('network/member?id='+alice,{user:null});check(r.data.name==='Alice'&&r.data.followers===1&&r.data.posts===1,'public profile server counts');check(Object.keys(r.data).sort().join(',')==='followers,following,id,name,posts','public profile has only allowlisted fields');check((await request('network/member?id=bad')).status===400,'invalid member');check((await request('link',{body:{kind:'follow',target:alice,active:true}})).status===400,'no self-follow');
await request('link',{user:'B',body:{kind:'block',target:alice,active:true}});check((await request('network/feed',{user:'B'})).data.posts.length===0,'blocked authors hidden');check((await request('network/comments?id='+id,{user:'B'})).status===404,'blocked post thread hidden');await request('link',{user:'B',body:{kind:'block',target:alice,active:false}});
const cid=crypto.randomUUID();await request('comments',{user:'B',body:{id:cid,post:id,text:'Commento locale'}});r=await request('network/comments?id='+id);check(r.data.comments[0].name==='Bruno','thread resolves author');check((await request('network/feed?id='+id)).data.posts[0].comments_count===1,'server comment count');
db.prepare('UPDATE posts SET expires=? WHERE id=?').run(Date.now()-1,id);check((await request('network/feed?id='+id)).data.posts.length===0,'expired posts hidden');check((await request('network/comments?id='+id)).status===404,'expired thread hidden');check((await request('comments',{body:{id:crypto.randomUUID(),post:id,text:'Late'}})).status===404,'expired post cannot receive comments');check((await request('link',{body:{kind:'like',target:id,active:true}})).status===404,'expired post cannot receive likes');
const insert=db.prepare('INSERT INTO posts(id,author,text,city,kind,created) VALUES(?,?,?,?,?,?)'),stamp=Date.now();for(let i=0;i<43;i++)insert.run(crypto.randomUUID(),alice,'Tie '+i,'Milano','Osservazione',stamp);let cursor='',seen=[];do{r=await request('network/feed?city=Milano'+(cursor?'&cursor='+cursor:''));seen.push(...r.data.posts.map(p=>p.id));cursor=r.data.cursor}while(cursor);check(seen.length===43&&new Set(seen).size===43,'composite cursor loses no equal-timestamp posts');check((await request('network/feed?cursor=broken')).status===400,'bad cursor rejected');
const clipID=crypto.randomUUID();function form(id=clipID,valid=true){const f=new FormData();for(const[k,v]of Object.entries({id,text:'Video test',city:'Roma',kind:'Osservazione'}))f.append(k,v);const bytes=new Uint8Array(64);if(valid)bytes.set(new TextEncoder().encode('ftyp'),4);f.append('file',new Blob([bytes],{type:'video/mp4'}),'test.mp4');return f}
check((await request('network/clip',{body:form(),user:null})).status===401,'video requires auth');check((await request('network/clip',{body:form(),headers:{origin:'https://evil.invalid'}})).status===403,'video origin enforced');check((await request('network/clip',{body:form(crypto.randomUUID(),false)})).status===400,'video signature checked');
r=await request('network/clip',{body:form()});check(r.status===200,'video stores in R2');check((await request('network/clip',{body:form()})).status===200,'video idempotency');check(db.prepare('SELECT COUNT(*) n FROM posts WHERE id=?').get(clipID).n===1,'retry creates one post');check((await request('network/clip',{user:'B',body:form()})).status===409,'cannot reuse another author id');
r=await request('network/video/'+clipID,{user:null,headers:{range:'bytes=4-7'}});check(r.status===206&&new TextDecoder().decode(r.data)==='ftyp','video range playback');check(r.headers.get('content-range')==='bytes 4-7/64','range headers');check(r.headers.get('cache-control')==='private,no-store','private media no cache');check((await request('network/video/'+clipID,{headers:{range:'bytes=70-'}})).status===416,'invalid range rejected');check((await request('network/video/'+clipID,{headers:{range:'bytes=-0'}})).status===416,'empty suffix rejected');check((await request('network/video/'+clipID,{headers:{range:'bytes=-4'}})).data.length===4,'suffix range');check((await request('network/video/'+clipID,{method:'HEAD'})).data.length===0,'HEAD no body');
await request('link',{user:'B',body:{kind:'block',target:alice,active:true}});check((await request('network/video/'+clipID,{user:'B'})).status===404,'blocked video hidden');await request('delete',{body:{id:clipID}});check((await request('network/video/'+clipID,{user:null})).status===404,'deleted video unavailable');check((await request('network/feed?id='+clipID,{user:null})).data.posts.length===0,'deleted deep link unavailable');
check((await request('network/clip',{body:form(crypto.randomUUID())})).status===200,'fourth upload attempt allowed');check((await request('network/clip',{body:form(crypto.randomUUID())})).status===429,'video upload rate limit');
console.log(checks+' social-feed checks passed: filters, pagination, profiles, expiry, uploads, ownership, ranges, deletion and rate limits.');
