import './tools/rainbow-client.test.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import tzlookup from 'tz-lookup';
import {providerMarkup,providerBrief} from './dist/map-provider.js';
import {forecastSource,weatherDescription} from './dist/weather-tools.js';
import {weatherAge} from './dist/map-city-labels.js';
const api=vm.runInNewContext(fs.readFileSync('server/forecast-history.js','utf8')+'\n'+fs.readFileSync('server/rainbow-provider.js','utf8')+';({rainbowForecast,rainbowCondition})',{Date,Intl,Map,rainbowTimezone:tzlookup});
const at=Date.parse('2026-09-23T12:00:00Z');
const hour={validAt:at,validUntil:at+3600000,temperature:0,feelsLike:-1,humidity:0,windKmh:36,gustKmh:54,windDirection:0,pressureHpa:1013,visibilityMeters:8000,precipitationMm:0,precipitationProbability:0,uv:3,condition:'Clear'};
const input={hourly:Array.from({length:168},(_,i)=>({...hour,validAt:at+i*3600000,validUntil:at+(i+1)*3600000})),forThisHour:hour,issuedAt:at,sourceURL:'https://developer.rainbow.ai/'};
const rome=api.rainbowForecast(input,{latitude:41.9,longitude:12.5});
const tokyo=api.rainbowForecast(input,{latitude:35.68,longitude:139.69});
assert.equal(rome.timezone,'Europe/Rome');assert.equal(rome.current.time,'2026-09-23T14:00');
assert.equal(tokyo.timezone,'Asia/Tokyo');assert.equal(tokyo.current.time,'2026-09-23T21:00');
assert.equal(rome.current.temperature_2m,0);assert.equal(rome.current.surface_pressure,null);assert.equal(rome.current.pressure_msl,1013);
assert.equal(rome.daily.available_hours[0],10);assert.equal(rome.daily.sunrise[0],null);assert.equal(rome.hourly.time.length,168);
const future=Date.now()+86400000;
const providerDays=api.rainbowForecast({...input,days:[{validAt:future,validUntil:future+86400000,temperatureMin:12,temperatureMax:24,precipitationMm:2,precipitationProbability:40,uv:4,condition:'Rain'}]},{latitude:41.9,longitude:12.5});
assert.equal(providerDays.daily.temperature_2m_min[0],12);assert.equal(providerDays.daily.temperature_2m_max[0],24);assert.equal(providerDays.daily.aggregation,'provider');assert.ok(providerDays.daily.period_start[0]);
assert.equal(api.rainbowCondition('Hail')[0],null,'hail alone must not fabricate thunder');
assert.equal(forecastSource(rome),'Rainbow Weather');assert.match(weatherDescription(rome.current),/previsione/);
assert.throws(()=>api.rainbowForecast({...input,forThisHour:null},{latitude:41.9,longitude:12.5}),/questa ora/);
const current={...rome.current,time:new Date(at).toISOString()};
assert.equal(weatherAge(current,at+59*60000).stale,false);assert.equal(weatherAge(current,at+3600000).stale,true);
const panel={source:'Rainbow Weather',status:'available',kind:'forecast',timezone:rome.timezone,validAt:at,validUntil:at+3600000,issuedAt:at,temperature:0,condition:'Sereno'};
assert.match(providerMarkup(panel),/Non è una misura osservata/);assert.match(providerBrief({name:'Roma'},panel),/PREVISIONE ORARIA/);
console.log('Rainbow provider: Rome/Tokyo time zones, partial days, forecast semantics, missing fields and map validity passed.');
const {createLocalEnvironment}=await import('./tools/local-preview.mjs');
const {default:worker}=await import('./dist/server/index.js');
const {default:os}=await import('node:os');const {default:path}=await import('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rainbow-test-')),local=createLocalEnvironment(process.cwd(),dir),env={...local.env,RAINBOW_API_KEY:'fixture-not-secret',WEATHERAPI_KEY:'unused-fixture'},original=globalThis.fetch;
let calls=0;const epoch=Math.floor(Date.now()/3600000)*3600;
globalThis.fetch=async(url,init)=>{assert.equal(new URL(url).hostname,'api.rainbow.ai');calls++;assert.equal(init.headers['Ocp-Apim-Subscription-Key'],'fixture-not-secret');return new Response(JSON.stringify({generatedAtTimestamp:epoch,location:{lat:41.9,lon:12.5},units:{temperature:'celsius',windSpeed:'meter_per_second'},timelines:{hourly:Array.from({length:168},(_,i)=>({startTimestamp:epoch+i*3600,temperature:20,windSpeed:2,condition:'Clear'}))}}));};
const call=async suffix=>{const r=await worker.fetch(new Request('https://test.invalid/api/forecast'+suffix),env);return {status:r.status,data:await r.json()}};
try{
 assert.equal((await call('/provider')).data.source,'Rainbow Weather');
 const f=await call('?lat=41.9&lon=12.5');assert.equal(f.status,200);assert.equal(f.data.source,'Rainbow Weather');assert.equal(f.data.timezone,'Europe/Rome');
 const c=await call('/current?lat=41.9&lon=12.5');assert.equal(c.data.status,'available');assert.equal(c.data.kind,'forecast');assert.equal(c.data.observedAt,null);assert.equal(calls,1,'forecast and map share persistent cache');
 assert.equal(JSON.stringify(c).includes('fixture-not-secret'),false);
 const rainbowFetch=globalThis.fetch;let aiInput;
 globalThis.fetch=async(url,init)=>{if(String(url)==='https://api.openai.com/v1/responses'){const body=JSON.parse(init.body);aiInput=JSON.parse(body.input);return Response.json({output:[{content:[{type:'output_text',text:'Previsione Rainbow Weather.'}]}]})}return rainbowFetch(url,init)};
 const ai=await worker.fetch(new Request('https://test.invalid/api/ai',{method:'POST',headers:{origin:'https://test.invalid','content-type':'application/json','oai-authenticated-user-id':'rainbow-test','oai-authenticated-user-email':'test@example.invalid'},body:JSON.stringify({question:'Spiega il dato',city:'Roma',latitude:41.9,longitude:12.5,section:'weather',task:'explain'})}),{...env,WEATHERAPI_KEY:'',OPENAI_API_KEY:'test-only'});
 assert.equal(ai.status,200);assert.equal(aiInput.forecast.source,'Rainbow Weather','Lente uses Rainbow even without WeatherAPI key');assert.equal(aiInput.forecast.kind,'forecast');assert.equal(calls,1,'AI reuses forecast cache');
 globalThis.fetch=rainbowFetch;

 await env.DB.prepare('UPDATE limits SET count=5000 WHERE key=?').bind('rainbow-weather-month:'+new Date().toISOString().slice(0,7)).run();
 assert.equal((await call('/current?lat=42&lon=13')).data.status,'unavailable');assert.equal(calls,1,'monthly quota blocks upstream request');
}finally{globalThis.fetch=original;local.close();fs.rmSync(dir,{recursive:true,force:true});}
console.log('Rainbow Worker: provider precedence, shared cache, secret header and quota enforcement passed.');
