import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createLocalEnvironment} from './tools/local-preview.mjs';
import worker from './dist/server/index.js';
const dir=mkdtempSync(path.join(tmpdir(),'school-')),local=createLocalEnvironment(process.cwd(),dir),env=local.env;
const nativeNow=Date.now,nativeFetch=globalThis.fetch;let now=Date.parse('2026-09-16T12:00:00Z');Date.now=()=>now;const sent=[];
globalThis.fetch=async(url,options)=>{if(String(url).startsWith('https://fcm.googleapis.com/')){sent.push({url,options});return new Response(null,{status:201})}throw Error('Unexpected external request in test')};
const hash=s=>createHash('sha256').update(s).digest('hex');
const call=async(p,b,who='',cookie='',origin='https://preview.invalid')=>{const h=new Headers({origin});if(who){h.set('oai-authenticated-user-id',who);h.set('oai-authenticated-user-email','test@example.invalid')}if(cookie)h.set('cookie',cookie);if(b!==undefined)h.set('content-type','application/json');const r=await worker.fetch(new Request('https://preview.invalid/api/'+p,{method:b===undefined?'GET':'POST',headers:h,body:b===undefined?undefined:JSON.stringify(b)}),env);return {status:r.status,body:await r.json(),cookie:r.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ')}};
const point=()=>({latitude:42.96,longitude:13.88,accuracy:20,locatedAt:now,consent:true});
const question=()=>({...point(),id:crypto.randomUUID(),city:'San Benedetto del Tronto'});
const answer=(extra={})=>({...point(),id:crypto.randomUUID(),answer:'Non si sa ancora',sameTown:true,...extra});
async function seedAlert(level){const properties={'Nome zona':'TEST ONLY','Rappresentata nella mappa':level?'allerta arancione':'nessuna allerta'},geometry=JSON.stringify({type:'Polygon',coordinates:[[[13,42],[15,42],[15,44],[13,44],[13,42]]],properties});await env.DB.prepare('INSERT OR REPLACE INTO dpc_bulletins VALUES(?,?,?,?,?,?,0)').bind('2026-09-16','test','20260916_1200_today','https://example.invalid/fixture',now,now).run();await env.DB.prepare('INSERT OR REPLACE INTO dpc_zones VALUES(?,?,?)').bind('test',0,geometry).run()}
try{
 for(const p of ['questions','questions/presence','answer-push/subscribe'])assert.equal((await call(p,{})).status,401);
 for(const p of ['questions/mine','questions/nearby','questions/notifications'])assert.equal((await call(p)).status,401);
 const cookie=(await call('sky/session',{},'parent')).cookie,witnessCookie=(await call('sky/session',{},'witness')).cookie;
 await seedAlert(0);assert.equal((await call('questions',question(),'parent',cookie)).status,409);
 await seedAlert(2);const body=question(),created=await call('questions',body,'parent',cookie);assert.equal(created.status,201);assert.equal(created.body.people,0);const id=created.body.question.id;
 assert.equal((await call('questions',body,'parent',cookie)).status,200);assert.equal((await call('questions',question(),'parent',cookie)).status,429);
 assert.equal((await call('questions/nearby',undefined,'witness',witnessCookie)).body.locationRequired,true);
 assert.equal((await call('questions/presence',{...point(),consent:false},'witness',witnessCookie)).status,400);
 assert.equal((await call('questions/presence',point(),'witness',witnessCookie)).status,200);
 const nearby=await call('questions/nearby',undefined,'witness',witnessCookie);assert.equal(nearby.body.questions[0].id,id);for(const k of ['author','lat','lon'])assert.equal(k in nearby.body.questions[0],false);
 assert.equal((await call('questions/'+id+'/answers',answer({latitude:44}),'witness',witnessCookie)).status,403);
 assert.equal((await call('questions/'+id+'/answers',answer({sameTown:false}),'witness',witnessCookie)).status,400);
 assert.equal((await call('questions/'+id+'/answers',answer({url:'javascript:alert(1)'}),'witness',witnessCookie)).status,400);
 assert.equal((await call('questions/'+id+'/answers',answer({locatedAt:now-180000}),'witness',witnessCookie)).status,400);
 assert.equal((await call('questions/'+id+'/answers',answer(),'witness',witnessCookie,'https://evil.invalid')).status,403);
 const a=answer({answer:'Aperte',url:'https://www.comune.example.it/ordinanza'});assert.equal((await call('questions/'+id+'/answers',a,'witness',witnessCookie)).status,200);
 assert.equal((await call('questions/'+id+'/answers',a,'witness',witnessCookie)).status,200);
 assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM zone_answers').bind().first()).n,1);assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM answer_notices').bind().first()).n,1);assert.equal(sent.length,0);
 assert.equal((await call('questions/'+id+'/answers',answer(),'other')).status,200);
 const mine=(await call('questions/mine',undefined,'parent',cookie)).body.questions;assert.equal(mine[0].answers[0].url,a.url);assert.equal('author' in mine[0].answers[0],false);
 let notes=(await call('questions/notifications',undefined,'parent',cookie)).body.notifications;assert.equal(notes.length,1);
 await call('questions/seen',{id:notes[0].id},'witness',witnessCookie);assert.equal((await call('questions/notifications',undefined,'parent',cookie)).body.notifications.length,1);
 await call('questions/seen',{id:notes[0].id},'parent',cookie);assert.equal((await call('questions/notifications',undefined,'parent',cookie)).body.notifications.length,0);
 assert.equal((await call('answer-push/subscribe',{endpoint:'https://fcm.googleapis.com/fcm/send/test'},'parent',cookie)).status,403);
 await env.DB.prepare('INSERT INTO sky_reports(id,author,lat,lon,city,level,kind,created,expires) VALUES(?,?,?,?,?,?,?,?,?)').bind('test-report',hash('parent'),4296,1388,'Test',0,'asciutto',now,now+7200000).run();
 const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);env.WEB_PUSH_PRIVATE_JWK=JSON.stringify(await crypto.subtle.exportKey('jwk',keys.privateKey));env.WEB_PUSH_PUBLIC_KEY=Buffer.from(await crypto.subtle.exportKey('raw',keys.publicKey)).toString('base64url');
 for(const endpoint of ['http://fcm.googleapis.com/x','https://127.0.0.1/x','https://evil.invalid/x','https://fcm.googleapis.com.evil.invalid/x'])assert.equal((await call('answer-push/subscribe',{endpoint},'parent',cookie)).status,400);
 assert.equal((await call('answer-push/subscribe',{endpoint:'https://fcm.googleapis.com/fcm/send/test'},'parent',cookie)).status,200);
 for(let i=0;i<3;i++){const qid=crypto.randomUUID();await env.DB.prepare('INSERT INTO zone_questions(id,author,city,lat,lon,day,created,expires) VALUES(?,?,?,?,?,?,?,?)').bind(qid,hash('parent'),'Test',4296,1388,'2026-09-17',now,now+7200000).run();assert.equal((await call('questions/'+qid+'/answers',answer(),'witness',witnessCookie)).status,200)}
 assert.equal(sent.length,2,'strict daily push cap');
 const jwt=sent[0].options.headers.Authorization.match(/vapid t=(.*), k=/)[1],parts=jwt.split('.');assert.equal(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},keys.publicKey,Buffer.from(parts[2],'base64url'),new TextEncoder().encode(parts[0]+'.'+parts[1])),true);assert.equal(JSON.parse(Buffer.from(parts[1],'base64url')).aud,'https://fcm.googleapis.com');assert.equal(sent[0].options.redirect,'error');assert.equal(sent[0].options.body,undefined,'no private payload');
 await call('answer-push/later',{},'parent',cookie);const config=(await call('answer-push/config',undefined,'parent',cookie)).body;assert.equal(config.enabled,false);assert.equal(config.later,now+604800000);
 await call('questions/answers/'+a.id+'/flag',{},'other');assert.equal((await call('questions/mine',undefined,'parent',cookie)).body.questions.find(r=>r.id===id).answers.some(r=>r.id===a.id),false);
 env.MODERATION_PASSWORD_HASH=hash('test-password');const admin=(await call('moderation/login',{password:'test-password'})).cookie;
 assert.equal((await call('moderation/reports',undefined,'',admin)).body.reports.some(r=>r.id===a.id&&r.source==='schools'&&r.hidden===1),true);
 assert.equal((await call('moderation/remove',{source:'schools',id:a.id},'',admin)).status,200);
 await env.DB.prepare('UPDATE zone_questions SET expires=? WHERE id=?').bind(now-1,id).run();assert.equal((await call('questions/'+id+'/answers',answer(),'other')).status,410);
 assert.equal((await call('questions/mine',undefined,'parent',cookie)).body.questions.some(r=>r.id===id),false);
 now=Date.parse('2026-09-16T21:00:00Z');await call('answer-push/subscribe',{endpoint:'https://fcm.googleapis.com/fcm/send/test'},'parent',cookie);const qid=crypto.randomUUID();await env.DB.prepare('INSERT INTO zone_questions(id,author,city,lat,lon,day,created,expires) VALUES(?,?,?,?,?,?,?,?)').bind(qid,hash('parent'),'Test',4296,1388,'2026-09-17',now,now+7200000).run();await call('questions/'+qid+'/answers',answer(),'witness',witnessCookie);assert.equal(sent.length,2,'quiet hours suppress push');
 now=Date.parse('2026-09-16T12:00:00Z');
 const reporterCookie=(await call('sky/session',{},'reporter')).cookie;
 const report=()=>({...point(),id:crypto.randomUUID(),city:'Roma',level:2,options:[]});
 const first=(await call('sky/reports',report(),'reporter',reporterCookie)).body.report;
 assert.equal((await call('answer-push/subscribe',{endpoint:'https://fcm.googleapis.com/fcm/send/feedback-test',answers:false},'reporter',reporterCookie)).status,200);
 assert.equal((await call('answer-push/feedback',{enabled:true},'reporter',reporterCookie)).status,200);
 await call('sky/reports/'+first.id+'/confirm',point(),'witness',witnessCookie);assert.equal(sent.length,3);
 await call('sky/reports/'+first.id+'/confirm',point(),'witness',witnessCookie);assert.equal(sent.length,3,'duplicate confirmation does not send again');
 const feedbackConfig=(await call('answer-push/config',undefined,'reporter',reporterCookie)).body;assert.equal(feedbackConfig.enabled,false);assert.equal(feedbackConfig.feedbackEnabled,true);
 assert.equal((await call('answer-push/feedback',undefined,'reporter',reporterCookie)).body.notices[0].confirms,1);
 await call('answer-push/disable',{},'reporter',reporterCookie);
 assert.ok(await env.DB.prepare('SELECT device FROM answer_subscriptions WHERE actor=?').bind(hash('reporter')).first(),'disabling school answers preserves confirmation subscription');
 for(let i=0;i<2;i++){const row=(await call('sky/reports',report(),'reporter',reporterCookie)).body.report;await call('sky/reports/'+row.id+'/confirm',point(),'witness',witnessCookie)}assert.equal(sent.length,4,'same two-per-day cap also applies to confirmations');
 console.log('School flow passed: alert gate, 30-minute limit, idempotency, GPS consent/distance/freshness, privacy, source ordering, first-answer notice, ownership, opt-in, endpoint allowlist, signed VAPID, cap/quiet hours, expiry and moderation.');
}finally{Date.now=nativeNow;globalThis.fetch=nativeFetch;local.close();rmSync(dir,{recursive:true,force:true})}
