const NETWORK_KINDS=['Osservazione','Domanda','Pioggia','Vento','Grandine','Neve','Cielo sereno','Allagamento','Temperatura','Fulmini'];
async function networkApi(req,env,url){
 const user=await identity(req),path=url.pathname,now=Date.now();
 if(path==='/api/network/feed'&&req.method==='GET'){
  const mode=url.searchParams.get('mode')||'all',city=clean(url.searchParams.get('city'),80),author=clean(url.searchParams.get('author'),64),id=clean(url.searchParams.get('id'),50),query=clean(url.searchParams.get('q'),100),cursor=url.searchParams.get('cursor');
  const timeWindow=url.searchParams.get('window');if(timeWindow&&timeWindow!=='2h')fail(400,'Intervallo non valido.');
  const clauses=['p.deleted=0','(p.expires IS NULL OR p.expires>?)','p.created<=?'],args=[now,now];
  if(timeWindow==='2h'){clauses.push('p.created>=?');args.push(now-7200000)}
  if(user){clauses.push("NOT EXISTS(SELECT 1 FROM links b WHERE b.user=? AND b.target=p.author AND b.kind='block')");args.push(user)}
  if(mode==='following'){if(!user)return json({posts:[],comments:[],links:[],cursor:null});clauses.push("EXISTS(SELECT 1 FROM links f WHERE f.user=? AND f.target=p.author AND f.kind='follow')");args.push(user)}
  if(mode==='saved'){if(!user)return json({posts:[],comments:[],links:[],cursor:null});clauses.push("EXISTS(SELECT 1 FROM links f WHERE f.user=? AND f.target=p.id AND f.kind='save')");args.push(user)}
  if(mode==='local'||city){clauses.push('p.city=? COLLATE NOCASE');args.push(city)}
  if(author){if(!/^[a-f0-9]{64}$/.test(author))fail(400,'Profilo non valido.');clauses.push('p.author=?');args.push(author)}
  if(id){clauses.push('p.id=?');args.push(id)}
  const topic=clean(url.searchParams.get('topic'),30);if(topic){if(!NETWORK_KINDS.includes(topic))fail(400,'Argomento non valido.');clauses.push('p.kind=?');args.push(topic)}
  const climate=clean(url.searchParams.get('climate'),20);if(climate){if(climate!=='rain')fail(400,'Canale meteo non valido.');clauses.push("p.kind='Pioggia' AND p.created>=?");args.push(now-7200000)}
  if(query){clauses.push('(instr(lower(p.text),lower(?))>0 OR instr(lower(p.city),lower(?))>0)');args.push(query,query)}
  if(cursor&&!id){const [time,key]=cursor.split('_');if(!/^\d{1,15}$/.test(time)||!/^[a-f0-9-]{36}$/.test(key||''))fail(400,'Pagina non valida.');clauses.push('(p.created<? OR (p.created=? AND p.id<?))');args.push(Number(time),Number(time),key)}
  const rows=(await q(env,`SELECT p.*,COALESCE(u.name,'Membro') name,(SELECT COUNT(*) FROM comments c WHERE c.post=p.id) comments_count,(SELECT COUNT(*) FROM links l WHERE l.target=p.id AND l.kind='like') likes,(SELECT COUNT(*) FROM links l WHERE l.target=p.id AND l.kind='heat') heat_count,(SELECT COUNT(*) FROM links l WHERE l.target=p.id AND l.kind='snow') snow_count,(SELECT COUNT(*) FROM links l WHERE l.target=p.id AND l.kind='storm') storm_count,(SELECT COUNT(*) FROM links l WHERE l.target=p.id AND l.kind='confirm') confirms,(SELECT COUNT(*) FROM links l WHERE l.target=p.id AND l.kind='dispute') disputes FROM posts p LEFT JOIN profiles u ON p.author=u.id WHERE ${clauses.join(' AND ')} ORDER BY p.created DESC,p.id DESC LIMIT 21`,...args).all()).results;
  const posts=rows.slice(0,20),last=posts.at(-1),links=user?(await q(env,'SELECT kind,target FROM links WHERE user=?',user).all()).results:[];
  return json({posts,links,cursor:rows.length>20?last.created+'_'+last.id:null});
 }
 if(path==='/api/network/member'&&req.method==='GET'){const id=clean(url.searchParams.get('id'),64);if(!/^[a-f0-9]{64}$/.test(id))fail(400,'Profilo non valido.');const p=await q(env,"SELECT id,name,(SELECT COUNT(*) FROM links WHERE target=profiles.id AND kind='follow') followers,(SELECT COUNT(*) FROM links WHERE user=profiles.id AND kind='follow') following,(SELECT COUNT(*) FROM posts WHERE author=profiles.id AND deleted=0 AND (expires IS NULL OR expires>?)) posts FROM profiles WHERE id=?",now,id).first();if(!p)fail(404,'Profilo non disponibile.');return json(p)}
 if(path==='/api/network/comments'&&req.method==='GET'){const id=clean(url.searchParams.get('id'),50);const p=await q(env,'SELECT author FROM posts WHERE id=? AND deleted=0 AND (expires IS NULL OR expires>?)',id,now).first();if(!p)fail(404,'Post non disponibile.');if(user&&await q(env,"SELECT user FROM links WHERE user=? AND target=? AND kind='block'",user,p.author).first())fail(404,'Post nascosto.');const rows=(await q(env,"SELECT c.*,COALESCE(p.name,'Membro') name FROM comments c LEFT JOIN profiles p ON p.id=c.author WHERE c.post=? AND (? IS NULL OR NOT EXISTS(SELECT 1 FROM links b WHERE b.user=? AND b.target=c.author AND b.kind='block')) ORDER BY c.created DESC LIMIT 100",id,user,user).all()).results;return json({comments:rows.reverse()})}
 if(path.startsWith('/api/network/video/')&&['GET','HEAD'].includes(req.method)){
  const id=path.split('/').pop(),p=await q(env,'SELECT video,author FROM posts WHERE id=? AND deleted=0 AND (expires IS NULL OR expires>?)',id,now).first();if(!p?.video)fail(404,'Video non disponibile.');if(user&&await q(env,"SELECT user FROM links WHERE user=? AND target=? AND kind='block'",user,p.author).first())fail(404,'Contenuto nascosto.');const o=await env.BUCKET.get(p.video);if(!o)fail(404,'Video non disponibile.');const bytes=new Uint8Array(await o.arrayBuffer()),headers={'Content-Type':o.httpMetadata.contentType,'X-Content-Type-Options':'nosniff','Cache-Control':'private,no-store','Accept-Ranges':'bytes'};const range=req.headers.get('range');if(range){const m=/^bytes=(\d*)-(\d*)$/.exec(range);if(!m||(!m[1]&&!m[2]))return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+bytes.length}});const start=m[1]?Number(m[1]):Math.max(0,bytes.length-Number(m[2])),end=m[1]&&m[2]?Math.min(Number(m[2]),bytes.length-1):bytes.length-1;if(start>end||start>=bytes.length)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+bytes.length}});return new Response(req.method==='HEAD'?null:bytes.slice(start,end+1),{status:206,headers:{...headers,'Content-Length':String(end-start+1),'Content-Range':`bytes ${start}-${end}/${bytes.length}`}})}return new Response(req.method==='HEAD'?null:bytes,{headers:{...headers,'Content-Length':String(bytes.length)}})
 }
 if(path!=='/api/network/clip'||req.method!=='POST')fail(404,'Funzione non disponibile.');
 if(!user)fail(401,'Accedi per pubblicare.');if(req.headers.get('origin')!==url.origin)fail(403,'Richiesta non autorizzata.');if(!req.headers.get('content-type')?.startsWith('multipart/form-data;'))fail(415,'Formato caricamento non valido.');if(!env.BUCKET)fail(503,'Archivio video non disponibile.');await quota(env,user,'clips',4);
 const reader=req.body?.getReader();if(!reader)fail(400,'Video mancante.');let size=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>8200000){await reader.cancel();fail(413,'Video troppo grande: massimo 8 MB.')}chunks.push(value)}const raw=new Uint8Array(size);let offset=0;for(const c of chunks){raw.set(c,offset);offset+=c.length}let data;try{data=await new Response(raw,{headers:{'Content-Type':req.headers.get('content-type')}}).formData()}catch{fail(400,'Caricamento non leggibile.')}
 const id=clean(data.get('id'),50),text=clean(data.get('text'),1000),city=clean(data.get('city'),80),kind=clean(data.get('kind'),30),file=data.get('file');
 if(!/^[a-f0-9-]{36}$/.test(id)||!text||!city||city.startsWith('Zona ')||!NETWORK_KINDS.includes(kind))fail(400,'Controlla descrizione, città e tipo.');if(!await q(env,'SELECT id FROM profiles WHERE id=?',user).first())fail(400,'Scegli prima il nome nel Profilo.');const existing=await q(env,'SELECT author FROM posts WHERE id=?',id).first();if(existing){if(existing.author!==user)fail(409,'Identificativo già usato.');return json({ok:true,id})}
 if(!file||typeof file.arrayBuffer!=='function'||file.size>8000000||file.size<16||!['video/mp4','video/webm'].includes(file.type))fail(400,'Scegli MP4 o WebM fino a 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const valid=file.type==='video/mp4'?new TextDecoder().decode(bytes.slice(4,8))==='ftyp':[26,69,223,163].every((b,i)=>bytes[i]===b);if(!valid)fail(400,'Il file non è un video supportato.');const key='clips/'+id;
 await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:file.type}});try{await q(env,'INSERT INTO posts(id,author,text,city,kind,video,created) VALUES(?,?,?,?,?,?,?)',id,user,text,city,kind,key,now).run()}catch(e){await env.BUCKET.delete(key);throw e}return json({ok:true,id});
}
