// H2 slice for E2: fixed school questions only. Coordinates are rounded before storage.
function schoolPoint(b,gps=false){if(!Number.isFinite(b.latitude)||!Number.isFinite(b.longitude)||Math.abs(b.latitude)>85||Math.abs(b.longitude)>180)fail(400,'Scegli una località valida.');if(gps&&(b.consent!==true||!Number.isFinite(b.accuracy)||b.accuracy<0||b.accuracy>1000||!Number.isFinite(b.locatedAt)||Math.abs(Date.now()-b.locatedAt)>120000))fail(400,'Serve una posizione recente e sufficientemente precisa, condivisa con il tuo consenso.');return {latitude:b.latitude,longitude:b.longitude}}
function schoolLink(value){if(value===undefined||value==='')return '';if(typeof value!=='string'||value.length>1200)fail(400,'Link non valido.');try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||!u.hostname.includes('.')||/^\d/.test(u.hostname)||u.hostname.endsWith('.local')||u.hostname.endsWith('.localhost'))throw Error();return u.href}catch{fail(400,'Inserisci un link HTTPS al sito del Comune.')}}
async function schoolCleanup(env){const cutoff=Date.now()-86400000;await db(env).batch([q(env,'DELETE FROM zone_answers WHERE question IN (SELECT id FROM zone_questions WHERE created<?)',cutoff),q(env,'DELETE FROM answer_notices WHERE created<?',cutoff),q(env,'DELETE FROM zone_questions WHERE created<?',cutoff),q(env,'DELETE FROM zone_presence WHERE created<?',cutoff)])}
async function schoolRows(env,rows,actor){return Promise.all(rows.map(async r=>({id:r.id,topic:r.topic,city:r.city,day:r.day,created:r.created,expires:r.expires,own:r.author===actor.id,answers:(await q(env,`SELECT a.id,a.answer,a.url,a.created FROM zone_answers a WHERE a.question=? AND a.hidden=0 AND a.deleted=0 AND NOT EXISTS(SELECT 1 FROM moderation_bans b WHERE b.key='actor:'||a.author) AND NOT EXISTS(SELECT 1 FROM sky_blocks b WHERE b.actor=? AND b.target=a.author) ORDER BY CASE WHEN a.url<>'' THEN 0 ELSE 1 END,a.created DESC LIMIT 100`,r.id,actor.id).all()).results}))) }
async function schoolQuestionsApi(req,env,url,ctx){const now=Date.now(),actor=await skyActor(req,env),path=url.pathname.slice('/api/questions'.length);if(!actor)fail(401,'Apri la domanda per iniziare una sessione.');if(!['GET','POST'].includes(req.method))fail(405,'Metodo non disponibile.');
 if(req.method==='GET'){
  if(path==='/mine'){const rows=(await q(env,'SELECT * FROM zone_questions WHERE author=? AND deleted=0 AND expires>? ORDER BY created DESC LIMIT 30',actor.id,now).all()).results;return json({questions:await schoolRows(env,rows,actor)})}
  if(path==='/nearby'){
   const presence=await q(env,'SELECT * FROM zone_presence WHERE actor=? AND created>?',actor.id,now-600000).first();if(!presence)return json({questions:[],locationRequired:true});
   const rows=(await q(env,`SELECT * FROM zone_questions r WHERE r.deleted=0 AND r.expires>? AND ABS(r.lat-?)<=6 AND ABS(r.lon-?)<=12 AND NOT EXISTS(SELECT 1 FROM moderation_bans b WHERE b.key='actor:'||r.author) AND NOT EXISTS(SELECT 1 FROM sky_blocks b WHERE b.actor=? AND b.target=r.author) ORDER BY r.created DESC LIMIT 100`,now,presence.lat,presence.lon,actor.id).all()).results.filter(r=>skyDistance({latitude:presence.lat/100,longitude:presence.lon/100},{latitude:r.lat/100,longitude:r.lon/100})<=5);
   return json({questions:await schoolRows(env,rows,actor),locationRequired:false});
  }
  if(path==='/notifications'){const pending=(await q(env,'SELECT id FROM answer_notices WHERE actor=? AND pushed=0 AND seen=0 AND created>? LIMIT 2',actor.id,now-7200000).all()).results;for(const n of pending){const job=sendSchoolPush(env,actor.id,n.id,url.origin).catch(()=>{});if(ctx?.waitUntil)ctx.waitUntil(job);else await job}const rows=(await q(env,'SELECT n.id,n.question,n.created,q.city,q.day,q.topic FROM answer_notices n JOIN zone_questions q ON q.id=n.question WHERE n.actor=? AND n.seen=0 AND q.deleted=0 AND q.expires>? AND EXISTS(SELECT 1 FROM zone_answers a WHERE a.question=q.id AND a.hidden=0 AND a.deleted=0) ORDER BY n.created DESC LIMIT 20',actor.id,now).all()).results;return json({notifications:rows})}
  fail(404,'Pagina non trovata.');
 }
 if(req.headers.get('origin')!==url.origin||!req.headers.get('content-type')?.includes('application/json'))fail(403,'Richiesta non autorizzata.');await quota(env,actor.id,'questions-write',45);const raw=await req.text();if(raw.length>4000)fail(413,'Richiesta troppo grande.');let b;try{b=JSON.parse(raw)}catch{fail(400,'Dati non validi.')}if(!b||typeof b!=='object')fail(400,'Dati non validi.');await schoolCleanup(env);
 if(path==='/presence'){const p=schoolPoint(b,true);await q(env,'INSERT INTO zone_presence VALUES(?,?,?,?) ON CONFLICT(actor) DO UPDATE SET lat=excluded.lat,lon=excluded.lon,created=excluded.created',actor.id,Math.round(p.latitude*100),Math.round(p.longitude*100),now).run();return json({ok:true})}
 if(path==='/seen'){await q(env,'UPDATE answer_notices SET seen=1 WHERE actor=? AND id=?',actor.id,clean(b.id,36)).run();return json({ok:true})}
 if(path===''){
  const id=clean(b.id,36);if(!/^[a-f0-9-]{36}$/.test(id))fail(400,'Domanda non valida.');const old=await q(env,'SELECT * FROM zone_questions WHERE id=?',id).first();if(old){if(old.author!==actor.id)fail(409,'Identificativo già utilizzato.');if(old.deleted||old.expires<=now)fail(410,'Domanda scaduta.');return json({question:(await schoolRows(env,[old],actor))[0],retry:true})}
  const p=schoolPoint(b),city=clean(b.city,80);if(city.length<2||/[<>°]|\d{2}\.\d+/.test(city))fail(400,'Scegli il nome del comune.');
  const topic=b.topic||'school';if(!['school','rain','wind','cold'].includes(topic))fail(400,'Scegli una domanda sul cielo.');
  if(topic==='school'){if(await skyCountry(city,p.latitude,p.longitude)!=='IT')fail(400,'Non riusciamo a verificare questo comune italiano. Sceglilo dalla ricerca città e riprova.');
  const alert=await atmosphereSafety(p.latitude,p.longitude,env);if(!['CAUTION','EMERGENCY'].includes(alert.mode)||!(alert.level>0))fail(409,'Non risulta un’allerta attiva verificabile qui. Consulta il bollettino ufficiale.');}
  const reserved=await q(env,'INSERT INTO question_limits VALUES(?,?) ON CONFLICT(actor) DO UPDATE SET last=excluded.last WHERE question_limits.last<=? RETURNING actor',actor.id,now,now-1800000).first();if(!reserved)fail(429,'Puoi fare una domanda ogni 30 minuti.');
  const day=romeDate(now+(topic==='school'?86400000:0)),lat=Math.round(p.latitude*100),lon=Math.round(p.longitude*100);await q(env,'INSERT INTO zone_questions(id,author,city,lat,lon,day,created,expires,topic) VALUES(?,?,?,?,?,?,?,?,?)',id,actor.id,city,lat,lon,day,now,now+7200000,topic).run();
  const people=(await q(env,"SELECT actor,lat,lon FROM zone_presence p WHERE created>? AND actor<>? AND ABS(lat-?)<=6 AND ABS(lon-?)<=12 AND NOT EXISTS(SELECT 1 FROM moderation_bans b WHERE b.key='actor:'||p.actor)",now-600000,actor.id,lat,lon).all()).results.filter(r=>skyDistance(p,{latitude:r.lat/100,longitude:r.lon/100})<=5).length;
  const row=await q(env,'SELECT * FROM zone_questions WHERE id=?',id).first();return json({question:(await schoolRows(env,[row],actor))[0],people},201);
 }
 const match=path.match(/^\/([a-f0-9-]{36})\/answers$/);
 if(match){const row=await q(env,'SELECT * FROM zone_questions WHERE id=? AND deleted=0 AND expires>?',match[1],now).first();if(!row)fail(410,'La domanda è scaduta.');if(row.author===actor.id)fail(403,'Attendi la risposta di un’altra persona della zona.');const p=schoolPoint(b,true);if(skyDistance(p,{latitude:row.lat/100,longitude:row.lon/100})>5)fail(403,'Può rispondere chi si trova entro circa 5 km dalla zona.');if(row.topic==='school'&&b.sameTown!==true)fail(400,'Conferma che la risposta riguarda il comune indicato, non uno vicino.');if(!(row.topic==='school'?['Chiuse','Aperte','Non si sa ancora']:['Sì','No','Non so']).includes(b.answer))fail(400,'Scegli una delle tre risposte.');const link=row.topic==='school'?schoolLink(b.url):'';
  const id=clean(b.id,36);if(!/^[a-f0-9-]{36}$/.test(id))fail(400,'Risposta non valida.');await q(env,'INSERT OR IGNORE INTO zone_answers(id,question,author,answer,url,created) VALUES(?,?,?,?,?,?)',id,row.id,actor.id,b.answer,link,now).run();
  const saved=await q(env,'SELECT id FROM zone_answers WHERE question=? AND author=? AND deleted=0 AND hidden=0',row.id,actor.id).first();if(!saved)fail(409,'Risposta non disponibile.');
  const inserted=await q(env,'INSERT OR IGNORE INTO answer_notices(id,actor,question,created) VALUES(?,?,?,?) RETURNING id',crypto.randomUUID(),row.author,row.id,now).first();
  if(inserted){const job=sendSchoolPush(env,row.author,inserted.id,url.origin).catch(()=>{});if(ctx?.waitUntil)ctx.waitUntil(job);else await job}
  return json({ok:true,question:row.id});
 }
 const flag=path.match(/^\/answers\/([a-f0-9-]{36})\/flag$/);if(flag){await q(env,'UPDATE zone_answers SET hidden=1 WHERE id=? AND question IN(SELECT id FROM zone_questions WHERE expires>?)',flag[1],now).run();return json({ok:true})}
 fail(404,'Azione non disponibile.');
}
