// Human observations are independent of forecasts and expire after two hours.
const SKY_TTL=7200000;
const skyHash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),n=>n.toString(16).padStart(2,'0')).join('');
const skyDistance=(a,b)=>{const d=Math.PI/180,p=(b.latitude-a.latitude)*d,l=(b.longitude-a.longitude)*d;return 12742*Math.asin(Math.min(1,Math.sqrt(Math.sin(p/2)**2+Math.cos(a.latitude*d)*Math.cos(b.latitude*d)*Math.sin(l/2)**2)))};
function skyDeviceToken(req){const token=(req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('ms_sky_device='))?.slice(14);return /^[a-f0-9]{64}$/.test(token||'')?token:null}
async function skyDevice(req){const token=skyDeviceToken(req);return token?skyHash(token):''}
function skySessionResponse(req,url,body){const response=json(body);if(!skyDeviceToken(req)){const token=Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');response.headers.append('Set-Cookie','ms_sky_device='+token+'; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000'+(url.protocol==='https:'?'; Secure':''))}return response}
const skyReadColumns=`r.*,${skyProfessionColumn},(SELECT COUNT(*) FROM sky_confirmations c WHERE c.report=r.id) confirms,EXISTS(SELECT 1 FROM sky_confirmations c WHERE c.report=r.id AND (c.device=? OR c.actor=?)) confirmed`;
async function skyActor(req,env){const user=await identity(req);if(user)return {id:user,guest:0};const token=(req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('ms_sky='))?.slice(7);if(!/^[a-f0-9]{64}$/.test(token||''))return null;const id='g:'+await skyHash(token);return await q(env,'SELECT id,guest,first_report FROM sky_actors WHERE id=?',id).first()}
async function skyTrust(env,author){const r=await q(env,'SELECT COUNT(*) n,COUNT(DISTINCT witness) witnesses,COALESCE(AVG(agrees),.5) ratio FROM sky_evidence WHERE author=? AND created>?',author,Date.now()-30*86400000).first();return {weight:r.n>=6&&r.witnesses>=3?Math.max(.15,Math.min(1.5,r.ratio*1.5)):.75,hidden:r.n>=12&&r.witnesses>=4&&r.ratio<.2}}
function skyRow(r,actor){return {confirms:Number(r.confirms)||0,confirmed:!!r.confirmed,id:r.id,name:r.name||'',mestiere:Object.hasOwn(PROFESSION_TOPICS,r.mestiere)?r.mestiere:null,note:r.note||'',phenomenon:r.phenomenon||'',author:r.author,latitude:r.lat/100,longitude:r.lon/100,city:r.city,country:r.country,level:r.phenomenon?null:r.level,kind:r.kind,options:JSON.parse(r.options),photo:!!r.photo,created:r.created,expires:r.expires,own:r.author===actor?.id,visibility:r.hidden?'only-you':'public'}}
function skyVisibleSQL(){return `r.deleted=0 AND r.created<=? AND r.expires>? AND (r.hidden=0 OR r.author=?) AND NOT EXISTS(SELECT 1 FROM sky_blocks b WHERE b.actor=? AND b.target=r.author)`}
async function skyFirstInCity(env,row){const rows=(await q(env,'SELECT id FROM sky_reports WHERE city=? COLLATE NOCASE AND country IS ? AND deleted=0 AND hidden=0 AND created<=? AND expires>? LIMIT 2',row.city,row.country,Date.now(),Date.now()).all()).results;return rows.length===1&&rows[0].id===row.id}
async function skyStats(env){return await q(env,'SELECT COUNT(DISTINCT author) people,COUNT(DISTINCT country) countries FROM sky_reports WHERE deleted=0 AND hidden=0 AND created<=? AND expires>?',Date.now(),Date.now()).first()}
async function skyCountry(city,lat,lon){const known=ATLAS_CITIES.find(c=>c.name.toLocaleLowerCase()===city.toLocaleLowerCase()&&skyDistance({latitude:lat,longitude:lon},{latitude:c.latitude,longitude:c.longitude})<30);if(known)return known.country_code;try{const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:city,count:'5',language:'it',format:'json'}),{signal:AbortSignal.timeout(5000)});if(!r.ok)return null;const data=await r.json();const c=data.results?.find(c=>skyDistance({latitude:lat,longitude:lon},c)<30);return /^[A-Z]{2}$/.test(c?.country_code||'')?c.country_code:null}catch{return null}}
async function skyEvidenceUpdate(env,current,actor){if(actor.guest||current.phenomenon)return;const rows=(await q(env,`SELECT r.* FROM sky_reports r JOIN sky_actors a ON a.id=r.author WHERE r.author<>? AND a.guest=0 AND r.deleted=0 AND r.hidden=0 AND r.created BETWEEN ? AND ? AND r.expires>? AND ABS(r.lat-?)<=4 AND ABS(r.lon-?)<=8 ORDER BY r.created DESC LIMIT 100`,actor.id,current.created-900000,current.created,current.created,current.lat,current.lon).all()).results;
 const witnesses=new Set(),statements=[];for(const row of rows){if(witnesses.has(row.author)||skyDistance({latitude:row.lat/100,longitude:row.lon/100},{latitude:current.lat/100,longitude:current.lon/100})>3)continue;witnesses.add(row.author);if(row.phenomenon)continue;const agrees=Number(Math.abs(row.level-current.level)<=1);statements.push(q(env,'INSERT OR IGNORE INTO sky_evidence VALUES(?,?,?,?,?)',row.id,actor.id,row.author,agrees,current.created),q(env,'INSERT OR IGNORE INTO sky_evidence VALUES(?,?,?,?,?)',current.id,row.author,actor.id,agrees,current.created))}if(statements.length)await db(env).batch(statements);
 for(const id of [actor.id,...witnesses]){const trust=await skyTrust(env,id);if(trust.hidden)await q(env,'UPDATE sky_reports SET hidden=1 WHERE author=? AND expires>?',id,Date.now()).run()}}
async function skyApi(req,env,url,ctx){const path=url.pathname.slice('/api/sky/'.length),now=Date.now();let actor=await skyActor(req,env);
 if(!['GET','POST'].includes(req.method))fail(405,'Metodo non disponibile.');if(req.method==='POST'){if(req.headers.get('origin')!==url.origin)fail(403,'Richiesta non autorizzata.');if(!req.headers.get('content-type')?.includes('application/json'))fail(415,'Formato non valido.')}
 if(path==='session'&&req.method==='POST'){
  if(actor){await q(env,'INSERT OR IGNORE INTO sky_actors(id,guest,created) VALUES(?,?,?)',actor.id,actor.guest,now).run();return skySessionResponse(req,url,{actor:actor.id,guest:!!actor.guest,canReport:!actor.guest||!actor.first_report})}
  const network=req.headers.get('cf-connecting-ip');if(network)await quota(env,await skyHash(network+Math.floor(now/86400000)),'sky-session',12);
  const token=Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');const id='g:'+await skyHash(token);await q(env,'INSERT INTO sky_actors(id,guest,created) VALUES(?,1,?)',id,now).run();const response=skySessionResponse(req,url,{actor:id,guest:true,canReport:true});response.headers.append('Set-Cookie','ms_sky='+token+'; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000'+(url.protocol==='https:'?'; Secure':''));return response;
 }
 if(path==='reports'&&req.method==='GET'){
  const rows=(await q(env,'SELECT '+skyReadColumns+' FROM sky_reports r WHERE '+skyVisibleSQL()+' ORDER BY r.created DESC LIMIT 5000',await skyDevice(req),actor?.id||'',now,now,actor?.id||'',actor?.id||'').all()).results;
  return json({reports:rows.map(r=>skyRow(r,actor)),stats:await skyStats(env),asOf:now,truncated:rows.length===5000});
 }
 if(path==='nearby'&&req.method==='GET'){
  const lat=Number(url.searchParams.get('lat')),lon=Number(url.searchParams.get('lon'));if(!url.searchParams.has('lat')||!url.searchParams.has('lon')||!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)fail(400,'Zona non valida.');
  const angle=150/6371,ratio=Math.sin(angle)/Math.cos(lat*Math.PI/180),latRange=140,lonRange=Math.abs(lat)+angle*180/Math.PI>=90?18000:Math.min(18000,Math.ceil(Math.asin(Math.min(1,ratio))*180/Math.PI*100)+2);
  const rows=(await q(env,'SELECT '+skyReadColumns+' FROM sky_reports r WHERE '+skyVisibleSQL()+' AND ABS(r.lat-?)<=? AND MIN(ABS(r.lon-?),36000-ABS(r.lon-?))<=? ORDER BY r.created DESC LIMIT 5000',await skyDevice(req),actor?.id||'',now,now,actor?.id||'',actor?.id||'',lat*100,latRange,lon*100,lon*100,lonRange).all()).results;
  return json({reports:rows.map(r=>skyRow(r,actor)),truncated:rows.length===5000,asOf:now});
 }
 if(path==='zone'&&req.method==='GET'){
  const latitude=Number(url.searchParams.get('lat')),longitude=Number(url.searchParams.get('lon'));if(!url.searchParams.has('lat')||!url.searchParams.has('lon')||!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)fail(400,'Zona non valida.');
  const deltaLon=3/Math.max(1,111*Math.cos(latitude*Math.PI/180));const rows=(await q(env,'SELECT '+skyReadColumns+' FROM sky_reports r WHERE '+skyVisibleSQL()+' AND ABS(r.lat-?)<=4 AND ABS(r.lon-?)<=? ORDER BY r.created DESC LIMIT 500',await skyDevice(req),actor?.id||'',now,now,actor?.id||'',actor?.id||'',latitude*100,longitude*100,Math.ceil(deltaLon*100)+1).all()).results.filter(r=>skyDistance({latitude,longitude},{latitude:r.lat/100,longitude:r.lon/100})<=3);
  const latest=[...new Map(rows.filter(r=>!r.hidden).slice().reverse().map(r=>[r.author,r])).values()],weights=await Promise.all(latest.map(r=>skyTrust(env,r.author)));const {level,summary}=professionSummary(latest,weights);
  return json({reports:rows.map(r=>skyRow(r,actor)),people:latest.length,level,summary,asOf:now,radiusKm:3});
 }
 if(path.startsWith('photo/')&&req.method==='GET'){const id=path.slice(6),r=await q(env,'SELECT r.* FROM sky_reports r WHERE r.id=? AND '+skyVisibleSQL(),id,now,now,actor?.id||'',actor?.id||'').first();if(!r?.photo)fail(404,'Foto scaduta o non disponibile.');const o=await env.BUCKET?.get(r.photo);if(!o)fail(404,'Foto non disponibile.');return new Response(o.body,{headers:{'Content-Type':o.httpMetadata.contentType,'Cache-Control':'private,no-store','X-Content-Type-Options':'nosniff'}})}
 if(req.method!=='POST')fail(404,'Pagina non trovata.');if(!actor)fail(401,'Apri Racconta il tuo cielo per iniziare.');await quota(env,actor.id,'sky-write',30);const raw=await req.text();if(raw.length>1600000)fail(413,'Foto troppo grande.');let b;try{b=JSON.parse(raw)}catch{fail(400,'Dati non validi.')}if(!b||typeof b!=='object')fail(400,'Dati non validi.');
 if(path==='reports'){
  if(b.expectedActor&&b.expectedActor!==actor.id)fail(409,'La sessione è cambiata. Riapri la sessione originale per inviare.');
  const id=clean(b.id,36);if(!/^[a-f0-9-]{36}$/.test(id))fail(400,'Identificativo non valido.');const previous=await q(env,'SELECT r.*,'+skyProfessionColumn+' FROM sky_reports r WHERE r.id=?',id).first();if(previous){if(previous.author!==actor.id)fail(409,'Identificativo già utilizzato.');return json({report:skyRow(previous,actor),firstInCity:await skyFirstInCity(env,previous),stats:await skyStats(env)})}
  const observedAt=b.observedAt??now;if(!Number.isFinite(observedAt)||observedAt>now+60000)fail(400,'Ora della segnalazione non valida.');if(observedAt<=now-SKY_TTL)fail(410,'La segnalazione è scaduta: racconta il cielo che vedi adesso.');const created=Math.min(now,observedAt);
  if(actor.guest&&actor.first_report)fail(401,'Hai acceso il tuo primo punto. Accedi per raccontare ancora il cielo.');
  if(b.consent!==true||!Number.isInteger(b.level)||b.level<0||b.level>4||typeof b.latitude!=='number'||typeof b.longitude!=='number'||!Number.isFinite(b.latitude)||!Number.isFinite(b.longitude)||Math.abs(b.latitude)>90||Math.abs(b.longitude)>180)fail(400,'Controlla la zona e conferma la condivisione.');
  const city=clean(b.city,80);if(city.length<2)fail(400,'Scegli la città da raccontare.');const lat=Math.round(b.latitude*100),lon=Math.round(b.longitude*100),options=Array.isArray(b.options)?[...new Set(b.options.filter(x=>['sun','cloud','wind','hail','snow'].includes(x)))].slice(0,3):[],kind=options.includes('hail')?'hail':options.includes('snow')?'snow':b.level>0?'rain':options.includes('sun')?'sun':options.includes('wind')?'wind':options.includes('cloud')?'cloud':'dry';
  const phenomenon=clean(b.phenomenon,30),name=clean(b.name,40);if(phenomenon&&!['Pioggia','Grandine','Neve','Vento','Allagamento','Cielo sereno'].includes(phenomenon))fail(400,'Fenomeno non valido.');
  const country=await skyCountry(city,lat/100,lon/100),trust=await skyTrust(env,actor.id);let photo=null;
  if(b.photo){if(typeof b.photo!=='string'||!b.photo.startsWith('data:image/jpeg;base64,'))fail(400,'Usa una foto JPEG.');let bytes;try{bytes=Uint8Array.from(atob(b.photo.split(',')[1]),c=>c.charCodeAt(0))}catch{fail(400,'Foto non valida.')}if(bytes.length>1100000||bytes[0]!==255||bytes[1]!==216)fail(400,'Foto non valida o troppo grande.');bytes=stripMetadata(bytes,'image/jpeg');if(!env.BUCKET)fail(503,'Foto non disponibili.');photo='sky/'+actor.id+'/'+id+'/'+crypto.randomUUID();await env.BUCKET.put(photo,bytes,{httpMetadata:{contentType:'image/jpeg'}})}
  const reportKind=phenomenon?({'Pioggia':'rain','Grandine':'hail','Neve':'snow','Vento':'wind','Allagamento':'alert','Cielo sereno':'sun'}[phenomenon]):kind;
  const row={id,name,note:'',phenomenon,author:actor.id,lat,lon,city,country,level:b.level,kind:reportKind,options:JSON.stringify(options),photo,created,expires:created+SKY_TTL,hidden:Number(trust.hidden),deleted:0};
  try{await db(env).batch([q(env,'INSERT OR IGNORE INTO sky_actors(id,guest,created) VALUES(?,?,?)',actor.id,actor.guest,now),q(env,'UPDATE sky_actors SET first_report=? WHERE id=? AND first_report IS NULL',id,actor.id),q(env,`INSERT INTO sky_reports(id,author,lat,lon,city,country,level,kind,options,photo,created,expires,hidden,name,phenomenon,deleted) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0 WHERE EXISTS(SELECT 1 FROM sky_actors WHERE id=? AND (guest=0 OR first_report=?))`,id,actor.id,lat,lon,city,country,b.level,reportKind,row.options,photo,row.created,row.expires,row.hidden,name,phenomenon,actor.id,id)]);if(!await q(env,'SELECT id FROM sky_reports WHERE id=?',id).first()){if(photo)await env.BUCKET.delete(photo);fail(401,'Accedi per inviare altre segnalazioni.')}}catch(e){if(photo)await env.BUCKET.delete(photo);throw e}
  await skyEvidenceUpdate(env,row,actor);const saved=await q(env,'SELECT r.*,'+skyProfessionColumn+' FROM sky_reports r WHERE r.id=?',id).first();return json({report:skyRow(saved,actor),firstInCity:await skyFirstInCity(env,saved),stats:await skyStats(env)},201);
 }
 if(/^reports\/[a-f0-9-]{36}\/confirm$/.test(path)){
  const id=path.split('/')[1],device=await skyDevice(req);
  if(!device)fail(401,'Avvia la sessione prima di confermare.');
  if(b.consent!==true||typeof b.latitude!=='number'||typeof b.longitude!=='number'||!Number.isFinite(b.latitude)||!Number.isFinite(b.longitude)||Math.abs(b.latitude)>90||Math.abs(b.longitude)>180||!Number.isFinite(b.accuracy)||b.accuracy<0||b.accuracy>2000)fail(400,'Serve una posizione sufficientemente precisa per confermare.');
  const row=await q(env,'SELECT r.* FROM sky_reports r WHERE r.id=? AND r.hidden=0 AND '+skyVisibleSQL(),id,now,now,actor.id,actor.id).first();
  if(!row)fail(404,'Segnalazione scaduta o non disponibile.');
  if(row.author===actor.id)fail(403,'Non puoi confermare la tua segnalazione.');
  if(skyDistance(b,{latitude:row.lat/100,longitude:row.lon/100})>5)fail(403,'Puoi confermare solo entro 5 km.');
  await q(env,'INSERT OR IGNORE INTO sky_actors(id,guest,created) VALUES(?,?,?)',actor.id,actor.guest,now).run();
  // Unique device and actor constraints also protect concurrent/retried requests.
  await q(env,`INSERT OR IGNORE INTO sky_confirmations(report,device,actor,created) SELECT id,?,?,? FROM sky_reports WHERE id=? AND deleted=0 AND hidden=0 AND expires>?`,device,actor.id,now,id,now).run();
  // Preserve the existing anti-abuse policy: anonymous confirmations do not increase trust.
  if(!actor.guest)await q(env,`INSERT OR IGNORE INTO sky_evidence(report,witness,author,agrees,created) SELECT c.report,c.actor,r.author,1,c.created FROM sky_confirmations c JOIN sky_reports r ON r.id=c.report WHERE c.report=? AND c.device=? AND c.actor=? AND r.deleted=0 AND r.hidden=0 AND r.expires>?`,id,device,actor.id,now).run();
  const result=await q(env,'SELECT '+skyReadColumns+' FROM sky_reports r WHERE r.id=? AND r.deleted=0 AND r.hidden=0 AND r.expires>?',device,actor.id,id,now).first();
  if(!result)fail(404,'Segnalazione non più disponibile.');
  const notify=notifyReportConfirmation(env,row,url.origin).catch(()=>{});if(ctx?.waitUntil)ctx.waitUntil(notify);else await notify;
  return json({id,confirms:Number(result.confirms),confirmed:!!result.confirmed});
 }
 if(path==='note'){const note=clean(b.note,300),id=clean(b.id,36);const result=await q(env,'UPDATE sky_reports SET note=? WHERE id=? AND author=? AND deleted=0 AND expires>?',note,id,actor.id,now).run();if(!result.meta.changes)fail(403,'Puoi aggiornare solo una tua segnalazione attiva.');return json({ok:true})}
 if(path==='block'){const target=clean(b.target,70);if(!target||target===actor.id||!await q(env,'SELECT id FROM sky_actors WHERE id=?',target).first())fail(400,'Persona non valida.');await q(env,'INSERT OR IGNORE INTO sky_blocks VALUES(?,?)',actor.id,target).run();return json({ok:true})}
 if(path==='delete'){const r=await q(env,'SELECT photo FROM sky_reports WHERE id=? AND author=?',clean(b.id,36),actor.id).first();if(!r)fail(403,'Puoi eliminare soltanto le tue segnalazioni.');await q(env,'UPDATE sky_reports SET deleted=1 WHERE id=? AND author=?',b.id,actor.id).run();if(r.photo)await env.BUCKET?.delete(r.photo);return json({ok:true})}
 if(path==='flag'){if(actor.guest&&!actor.first_report)fail(401,'Accedi o invia la tua prima osservazione per segnalare un abuso.');const id=clean(b.id,36),reason=clean(b.reason,200);if(!reason)fail(400,'Indica il motivo.');const r=await q(env,'SELECT author FROM sky_reports WHERE id=? AND deleted=0 AND expires>?',id,now).first();if(!r||r.author===actor.id)fail(400,'Segnalazione non disponibile.');await db(env).batch([q(env,'INSERT OR IGNORE INTO sky_flags VALUES(?,?,?,?)',actor.id,id,reason,now),q(env,'INSERT OR IGNORE INTO sky_blocks VALUES(?,?)',actor.id,r.author),q(env,'UPDATE sky_reports SET hidden=1 WHERE id=?',id)]);return json({ok:true,message:'Contenuto nascosto dalla vista pubblica e autore bloccato per te.'})}
 fail(404,'Azione non disponibile.');
}
