// Public-data cache is an optimization: restricted runtimes must still fetch the source.
function optionalPublicCache(){
 const open=async()=>globalThis.caches?.open?await globalThis.caches.open('meteosocial-public-v1'):globalThis.caches?.default;
 return {
  async match(key){try{return await (await open())?.match(key)}catch{return undefined}},
  async put(key,response){try{await (await open())?.put(key,response)}catch{/* Source response remains valid without caching. */}}
 };
}
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(s,m)=>{throw {status:s,message:m}};
const clean=(v,n)=>typeof v==='string'?v.trim().slice(0,n):'';
const db=env=>{if(!env.DB)fail(503,'Community temporaneamente non disponibile.');return env.DB};
const q=(env,s,...v)=>db(env).prepare(s).bind(...v);
async function identity(req){const raw=req.headers.get('oai-authenticated-user-id');if(!raw||!req.headers.get('oai-authenticated-user-email'))return null;const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function quota(env,user,type,max){const key=type+':'+user+':'+Math.floor(Date.now()/3600000);const r=await q(env,'INSERT INTO limits(key,count) VALUES(?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count',key).first();if(r.count>max)fail(429,'Hai raggiunto il limite per questa ora. Riprova più tardi.')}
async function api(req,env,url){const user=await identity(req),path=url.pathname;const isWrite=req.method!=='GET';if(isWrite){if(!user)fail(401,'Accedi con ChatGPT per partecipare.');if(req.headers.get('origin')!==url.origin)fail(403,'Richiesta non autorizzata.');if(!req.headers.get('content-type')?.includes('application/json'))fail(415,'Formato non valido.');}
if(path==='/api/capabilities'&&req.method==='GET')return json({radar:{configured:true,detail:'Radar RainViewer delle precipitazioni recenti: orario e copertura visibili. Non identifica la grandine né prevede le traiettorie.'},ai:{configured:!!env.OPENAI_API_KEY,detail:env.OPENAI_API_KEY?'OpenAI configurato. Disponibilità e qualità dipendono dal servizio.':'Manca il collegamento OpenAI per traduzioni e analisi immagini.'},...Object.fromEntries(Object.entries({nowcast:'Richiede celle tracciate e validazione delle traiettorie.',historicalRisk:'Richiede un archivio calibrato e verifiche statistiche.',push:'Richiede consenso, registrazione dispositivi e servizio di consegna.',socialImport:'Richiede API autorizzate e diritti sui contenuti.',carSensors:'Richiede app nativa, dispositivi compatibili e modello validato.',smartHome:'Richiede collegamento esplicito agli hub domestici.',nativeWidgets:'Richiede estensioni native iOS e Android.',marketplace:'Richiede partner, catalogo e registro premi verificato.'}).map(([k,detail])=>[k,{configured:k==='push'?!!(env.WEB_PUSH_PRIVATE_JWK&&env.WEB_PUSH_PUBLIC_KEY):false,detail:k==='push'?'Avvisi facoltativi per risposte sulle scuole e conferme ricevute, dopo la prima segnalazione. Massimo due al giorno. Avvisi prima dell’uscita e allerte ufficiali automatiche non ancora attivi.':detail}]))});
if(path==='/api/hail/watch'&&req.method==='GET')return hailWatches(req,env,user);
if(path==='/api/me')return json({id:user,profile:user?await q(env,'SELECT name FROM profiles WHERE id=?',user).first():null,vision:!!env.OPENAI_API_KEY,google3d:google3dEnabled(env),ai:!!(env.OPENAI_API_KEY||env.ANTHROPIC_API_KEY)});
if(path==='/api/posts'&&req.method==='GET'){const before=Number(url.searchParams.get('before'))||Date.now()+1;const result=await q(env,`SELECT p.*,COALESCE(u.name,'Membro') name,(SELECT COUNT(*) FROM links WHERE target=p.id AND kind='like') likes,(SELECT COUNT(*) FROM links WHERE target=p.id AND kind='heat') heat_count,(SELECT COUNT(*) FROM links WHERE target=p.id AND kind='snow') snow_count,(SELECT COUNT(*) FROM links WHERE target=p.id AND kind='storm') storm_count,(SELECT COUNT(*) FROM links WHERE target=p.id AND kind='confirm') confirms,(SELECT COUNT(*) FROM links WHERE target=p.id AND kind='dispute') disputes FROM posts p LEFT JOIN profiles u ON p.author=u.id WHERE p.deleted=0 AND (p.expires IS NULL OR p.expires>${Date.now()}) AND p.created<? ORDER BY p.created DESC LIMIT 40`,before).all();const ids=result.results.map(p=>p.id);let cs=[];if(ids.length)cs=(await q(env,`SELECT c.*,COALESCE(u.name,'Membro') name FROM comments c LEFT JOIN profiles u ON c.author=u.id WHERE c.post IN (${ids.map(()=>'?').join(',')}) ORDER BY c.created`,...ids).all()).results;const links=user?(await q(env,'SELECT target,kind FROM links WHERE user=?',user).all()).results:[];return json({posts:result.results,comments:cs,links,more:result.results.length===40})}
if(path.startsWith('/api/photo/')&&req.method==='GET'){const id=path.split('/').pop();const p=await q(env,'SELECT photo FROM posts WHERE id=? AND deleted=0 AND (expires IS NULL OR expires>?)',id,Date.now()).first();if(!p?.photo)fail(404,'Foto non disponibile.');const o=await env.BUCKET.get(p.photo);if(!o)fail(404,'Foto non disponibile.');return new Response(o.body,{headers:{'Content-Type':o.httpMetadata?.contentType||'image/jpeg','X-Content-Type-Options':'nosniff','Cache-Control':'private,no-store'}})}
if(!isWrite)fail(404,'Pagina non trovata.');let b;const text=await req.text();if(text.length>2200000)fail(413,'Contenuto troppo grande.');try{b=JSON.parse(text)}catch{fail(400,'Dati non validi.')}
if(path==='/api/profile'){const name=clean(b.name,40);if(name.length<2)fail(400,'Scrivi un nome di almeno due caratteri.');await q(env,'INSERT INTO profiles(id,name) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name',user,name).run();return json({ok:true})}
if(path==='/api/ai'){if(env.ANTHROPIC_API_KEY&&!env.OPENAI_API_KEY)return anthropicAnswer(env,user,b);return lenteAnswer(env,user,b)}
await quota(env,user,'social',60);
if(path.startsWith('/api/hail/')){if(req.method!=='POST')fail(405,'Usa POST per aggiornare la grandine.');return hailWrite(env,user,path,b)}
if(path==='/api/posts'){const id=clean(b.id,50),body=clean(b.text,1000),city=clean(b.city,80),kind=clean(b.kind,30);if(/^Zona [-\d.]+°/.test(city)||/[-\d]+\.\d+.*[-\d]+\.\d+/.test(city))fail(400,'Scegli un comune, non coordinate precise.');if(!/^[a-f0-9-]{36}$/.test(id)||!body||!city||!['Osservazione','Domanda','Pioggia','Vento','Grandine','Neve','Cielo sereno','Allagamento'].includes(kind))fail(400,'Controlla testo, località e tipo di post.');if(!await q(env,'SELECT id FROM profiles WHERE id=?',user).first())fail(400,'Scegli prima il nome nel Profilo.');const existing=await q(env,'SELECT author FROM posts WHERE id=?',id).first();if(existing){if(existing.author!==user)fail(409,'Identificativo già usato.');return json({ok:true})}let mapLat=null,mapLon=null;if(b.mapPoint!==undefined){const p=b.mapPoint;if(kind!=='Grandine'||!p||p.consent!==true||!Number.isFinite(p.latitude)||!Number.isFinite(p.longitude)||Math.abs(p.latitude)>85||Math.abs(p.longitude)>180)fail(400,'Conferma una zona valida per la mappa grandine.');mapLat=Math.round(p.latitude*100);mapLon=Math.round(p.longitude*100)}const hail= hailInput(b.hail,kind);let photo=null;
if(b.photo){if(typeof b.photo!=='string'||!/^data:image\/(jpeg|png|webp);base64,/.test(b.photo))fail(400,'Formato foto non valido.');const parts=b.photo.split(',');let bytes=Uint8Array.from(atob(parts[1]),c=>c.charCodeAt(0));if(bytes.length>1500000)fail(413,'Foto troppo grande: massimo 1,5 MB.');const mime=parts[0].slice(5,-7);const valid=mime==='image/jpeg'?bytes[0]===255&&bytes[1]===216:mime==='image/png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71:new TextDecoder().decode(bytes.slice(8,12))==='WEBP';if(!valid)fail(400,'Il file non è una foto valida.');if(!env.BUCKET)fail(503,'Caricamento foto non disponibile.');bytes=stripMetadata(bytes,mime);photo='photos/'+id;await env.BUCKET.put(photo,bytes,{httpMetadata:{contentType:mime}})}
try{const statement=q(env,'INSERT INTO posts(id,author,text,city,kind,photo,expires,created,map_lat,map_lon) VALUES(?,?,?,?,?,?,?,?,?,?)',id,user,body,city,kind,photo,b.rapid===true?Date.now()+7200000:null,Date.now(),mapLat,mapLon);if(hail)await db(env).batch([statement,q(env,'INSERT INTO hail_details(post,observed,size) VALUES(?,?,?)',id,hail.observed,hail.size)]);else await statement.run()}catch(e){if(photo)await env.BUCKET.delete(photo);throw e}return json({ok:true})}
if(path==='/api/comments'){const body=clean(b.text,500),post=clean(b.post,50),id=clean(b.id,50);if(!body||!/^[a-f0-9-]{36}$/.test(id))fail(400,'Commento non valido.');if(!await q(env,'SELECT id FROM posts WHERE id=? AND deleted=0 AND (expires IS NULL OR expires>?)',post,Date.now()).first())fail(404,'Post non disponibile.');await q(env,'INSERT OR IGNORE INTO comments(id,post,author,text,created) VALUES(?,?,?,?,?)',id,post,user,body,Date.now()).run();return json({ok:true})}
if(path==='/api/link'){const kind=clean(b.kind,10),target=clean(b.target,80);if(!['like','save','follow','block','confirm','dispute','heat','snow','storm'].includes(kind)||!target)fail(400,'Azione non valida.');if(['like','save','heat','snow','storm'].includes(kind)&&!await q(env,'SELECT id FROM posts WHERE id=? AND deleted=0 AND (expires IS NULL OR expires>?)',target,Date.now()).first())fail(404,'Post non disponibile.');if(kind==='follow'&&(target===user||!await q(env,'SELECT id FROM profiles WHERE id=?',target).first()))fail(400,'Scegli un altro profilo valido.');if(['confirm','dispute'].includes(kind)){const now=Date.now(),post=await q(env,'SELECT author,expires,created,kind FROM posts WHERE id=? AND deleted=0',target).first();if(!post||(post.expires!=null&&post.expires<=now)||post.created>now||post.created<=now-7200000)fail(400,'La segnalazione non è più attiva.');if(post.author===user)fail(400,'Non puoi confermare la tua segnalazione.');if(await q(env,"SELECT 1 FROM links WHERE user=? AND target=? AND kind='block'",user,post.author).first())fail(404,'Post non disponibile.');if(typeof b.active!=='boolean')fail(400,'Azione non valida.');const statements=[q(env,"DELETE FROM links WHERE user=? AND target=? AND kind IN ('confirm','dispute')",user,target)];if(b.active)statements.push(q(env,'INSERT INTO links(user,target,kind) VALUES(?,?,?)',user,target,kind));await db(env).batch(statements);return json({ok:true})}if(b.active===true)await q(env,'INSERT OR IGNORE INTO links(user,target,kind) VALUES(?,?,?)',user,target,kind).run();else await q(env,'DELETE FROM links WHERE user=? AND target=? AND kind=?',user,target,kind).run();return json({ok:true})}
if(path==='/api/delete'){const id=clean(b.id,50);const r=await q(env,'UPDATE posts SET deleted=1 WHERE id=? AND author=?',id,user).run();if(!r.meta.changes)fail(403,'Puoi eliminare soltanto i tuoi post.');return json({ok:true})}
if(path==='/api/flag'){const post=clean(b.post,50),reason=clean(b.reason,200);if(!reason)fail(400,'Indica un motivo.');if(!await q(env,'SELECT id FROM posts WHERE id=? AND deleted=0',post).first())fail(404,'Post non disponibile.');await q(env,'INSERT INTO flags(user,post,reason,created) VALUES(?,?,?,?) ON CONFLICT(user,post) DO UPDATE SET reason=excluded.reason',user,post,reason,Date.now()).run();return json({ok:true})}
fail(404,'Azione non disponibile.')}
export default {async fetch(req,env,ctx){const url=new URL(req.url);try{if(url.pathname==='/api/forecast'||url.pathname.startsWith('/api/forecast/'))return await forecastApi(req,env,url);if(url.pathname.startsWith('/z/'))return await publicZonePage(req,env,url);if(url.pathname.startsWith('/api/local-weather/'))return await localWeatherApi(req,env,url);if(url.pathname.startsWith('/api/moderation/'))return await moderationApi(req,env,url);if(url.pathname.startsWith('/api/')&&req.method!=='GET')await moderationCheckWrite(req,env);if(url.pathname==='/api/profilo')return await professionApi(req,env,url);if(url.pathname==='/api/domanda'||url.pathname.startsWith('/api/domanda/'))return await dailyQuestionApi(req,env,url);if(url.pathname.startsWith('/api/growth/'))return await growthApi(req,env,url);if(url.pathname==='/api/groups'||url.pathname.startsWith('/api/groups/'))return await groupsApi(req,env,url,ctx);if(url.pathname==='/api/questions'||url.pathname.startsWith('/api/questions/'))return await schoolQuestionsApi(req,env,url,ctx);if(url.pathname.startsWith('/api/answer-push/'))return await schoolPushApi(req,env,url);if(url.pathname.startsWith('/api/sky/'))return await skyApi(req,env,url,ctx);if(url.pathname==='/api/maps/google3d')return google3dConfig(req,env);if(url.pathname.startsWith('/api/mappa/'))return await mappaApi(req,env,url);if(url.pathname.startsWith('/api/atmosphere/'))return await atmosphereApi(req,env,url);if(url.pathname.startsWith('/api/fitcheck/'))return await fitcheckApi(req,env,url);if(url.pathname.startsWith('/api/studio/'))return await studioApi(req,env,url);if(url.pathname.startsWith('/api/pulse/'))return await pulseApi(req,env,url);if(url.pathname.startsWith('/api/atlas/'))return await atlasApi(req,env,url);if(url.pathname.startsWith('/api/network/'))return await networkApi(req,env,url);if(url.pathname.startsWith('/api/global/'))return await globalApi(req,env,url);if(url.pathname.startsWith('/api/social/'))return await socialApi(req,env,url);if(url.pathname.startsWith('/api/'))return await api(req,env,url);const path=url.pathname==='/'?'/index.html':url.pathname;const a=assets[path];if(!a)return new Response('Pagina non trovata',{status:404});const bytes=Uint8Array.from(atob(a.data),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'Content-Type':a.type,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}})}catch(e){if(!e.status)console.error('request_failed',url.pathname,e.message);return json({error:e.status?e.message:'Servizio temporaneamente non disponibile. La tua bozza è conservata.'},e.status||503)}}};

function stripMetadata(b,mime){
 const concat=chunks=>{const out=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let o=0;for(const c of chunks){out.set(c,o);o+=c.length}return out};
 if(mime==='image/jpeg'){const chunks=[b.slice(0,2)];let i=2;while(i<b.length){if(b[i]!==255)fail(400,'Foto JPEG non valida.');const marker=b[i+1];if(marker===218||marker===217){chunks.push(b.slice(i));break}if(i+4>b.length)fail(400,'Foto incompleta.');const len=(b[i+2]<<8)|b[i+3];if(len<2||i+len+2>b.length)fail(400,'Foto incompleta.');if(!(marker>=224&&marker<=239)&&marker!==254)chunks.push(b.slice(i,i+len+2));i+=len+2;}return concat(chunks)}
 if(mime==='image/png'){const chunks=[b.slice(0,8)];let i=8;while(i+12<=b.length){const len=new DataView(b.buffer,b.byteOffset+i,4).getUint32(0);if(i+len+12>b.length)fail(400,'Foto PNG incompleta.');const type=new TextDecoder().decode(b.slice(i+4,i+8));if(['IHDR','PLTE','IDAT','IEND','tRNS'].includes(type))chunks.push(b.slice(i,i+len+12));i+=len+12;if(type==='IEND')break}return concat(chunks)}
 const chunks=[b.slice(0,12)];let i=12;while(i+8<=b.length){const len=new DataView(b.buffer,b.byteOffset+i+4,4).getUint32(0,true),end=i+8+len+(len%2);if(end>b.length)fail(400,'Foto WebP incompleta.');const type=new TextDecoder().decode(b.slice(i,i+4));if(!['EXIF','XMP ','ICCP'].includes(type)){const c=b.slice(i,end);if(type==='VP8X')c[8]&=~44;chunks.push(c)}i=end;}const result=concat(chunks);new DataView(result.buffer).setUint32(4,result.length-8,true);return result;
}

