import { sqliteTable, text, integer, primaryKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),name:text('name').notNull()});
export const posts=sqliteTable('posts',{id:text('id').primaryKey(),author:text('author').notNull(),text:text('text').notNull(),city:text('city').notNull(),kind:text('kind').notNull(),photo:text('photo'),video:text('video'),mapLat:integer('map_lat'),mapLon:integer('map_lon'),expires:integer('expires'),created:integer('created').notNull(),deleted:integer('deleted').notNull().default(0)},t=>[index('posts_date').on(t.created),index('posts_author').on(t.author)]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),post:text('post').notNull().references(()=>posts.id,{onDelete:'cascade'}),author:text('author').notNull(),text:text('text').notNull(),created:integer('created').notNull()},t=>[index('comments_post').on(t.post)]);
export const links=sqliteTable('links',{user:text('user').notNull(),target:text('target').notNull(),kind:text('kind').notNull()},t=>[primaryKey({columns:[t.user,t.target,t.kind]}),index('links_target').on(t.target,t.kind)]);
export const flags=sqliteTable('flags',{user:text('user').notNull(),post:text('post').notNull(),reason:text('reason').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.user,t.post]})]);
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull()});
export const avatars=sqliteTable('avatars',{user:text('user').primaryKey(),bald:integer('bald').notNull().default(1),equipped:text('equipped').notNull().default('none')});
export const inventory=sqliteTable('inventory',{user:text('user').notNull(),item:text('item').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.user,t.item]})]);
export const referrals=sqliteTable('referrals',{invitee:text('invitee').primaryKey(),inviter:text('inviter').notNull(),created:integer('created').notNull()},t=>[index('referrals_inviter').on(t.inviter)]);
export const checkins=sqliteTable('checkins',{user:text('user').primaryKey(),id:text('id').notNull(),city:text('city').notNull(),lat:integer('lat').notNull(),lon:integer('lon').notNull(),caption:text('caption').notNull(),audio:text('audio').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull()},t=>[index('checkins_expires').on(t.expires)]);
export const shelters=sqliteTable('shelters',{id:text('id').primaryKey(),author:text('author').notNull(),name:text('name').notNull(),city:text('city').notNull(),lat:text('lat').notNull(),lon:text('lon').notNull(),details:text('details').notNull(),created:integer('created').notNull(),deleted:integer('deleted').notNull().default(0)},t=>[index('shelters_date').on(t.created)]);
export const translations=sqliteTable('translations',{post:text('post').notNull(),locale:text('locale').notNull(),text:text('text').notNull(),model:text('model').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.post,t.locale]})]);
export const assessments=sqliteTable('assessments',{post:text('post').primaryKey(),result:text('result').notNull(),model:text('model').notNull(),created:integer('created').notNull()});
export const memberships=sqliteTable('memberships',{user:text('user').primaryKey(),clan:text('clan').notNull(),created:integer('created').notNull()},t=>[index('memberships_clan').on(t.clan)]);
export const cityChallengeMembers=sqliteTable('city_challenge_members',{user:text('user').notNull(),week:text('week').notNull(),city:text('city').notNull()},t=>[primaryKey({columns:[t.user,t.week]}),index('challenge_members_week').on(t.week,t.city)]);
export const cityChallengeEntries=sqliteTable('city_challenge_entries',{post:text('post').primaryKey().references(()=>posts.id),user:text('user').notNull(),week:text('week').notNull(),day:text('day').notNull(),city:text('city').notNull()},t=>[uniqueIndex('challenge_user_day').on(t.user,t.week,t.day),index('challenge_week_city').on(t.week,t.city)]);

export const fitChecks=sqliteTable('fit_checks',{post:text('post').primaryKey().references(()=>posts.id,{onDelete:'cascade'}),lat:integer('lat').notNull(),lon:integer('lon').notNull(),tag:text('tag').notNull(),expires:integer('expires').notNull()},t=>[index('fit_checks_area').on(t.lat,t.lon),index('fit_checks_expiry').on(t.expires)]);

export const weatherRooms=sqliteTable('weather_rooms',{id:text('id').primaryKey(),city:text('city').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull(),sourceTime:text('source_time').notNull()},t=>[index('weather_rooms_expiry').on(t.expires)]);
export const weatherRoomMembers=sqliteTable('weather_room_members',{user:text('user').notNull(),room:text('room').notNull(),expires:integer('expires').notNull()},t=>[primaryKey({columns:[t.user,t.room]}),index('weather_room_member_expiry').on(t.expires)]);
export const weatherRoomMessages=sqliteTable('weather_room_messages',{id:text('id').primaryKey(),room:text('room').notNull(),user:text('user').notNull(),text:text('text').notNull(),created:integer('created').notNull(),deleted:integer('deleted').notNull().default(0)},t=>[index('weather_room_messages_order').on(t.room,t.created)]);
export const weatherRoomFlags=sqliteTable('weather_room_flags',{user:text('user').notNull(),message:text('message').notNull(),reason:text('reason').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.user,t.message]})]);
export const captureTickets=sqliteTable('capture_tickets',{id:text('id').primaryKey(),user:text('user').notNull(),city:text('city').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull(),used:integer('used').notNull().default(0),hash:text('hash')},t=>[index('capture_expiry').on(t.expires),index('capture_owner').on(t.user,t.created)]);

export const hailDetails=sqliteTable('hail_details',{post:text('post').primaryKey().references(()=>posts.id,{onDelete:'cascade'}),observed:integer('observed').notNull(),size:text('size').notNull().default('unknown'),ended:integer('ended')});
export const hailWatches=sqliteTable('hail_watches',{user:text('user').notNull(),slot:integer('slot').notNull(),name:text('name').notNull(),lat:integer('lat').notNull(),lon:integer('lon').notNull(),radius:integer('radius').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.user,t.slot]})]);

// Globo Vivo: additive tables, separate from the preserved post archive.
export const skyActors=sqliteTable('sky_actors',{id:text('id').primaryKey(),guest:integer('guest').notNull().default(0),firstReport:text('first_report'),created:integer('created').notNull()});
export const skyReports=sqliteTable('sky_reports',{name:text('name').notNull().default(''),note:text('note').notNull().default(''),phenomenon:text('phenomenon').notNull().default(''),id:text('id').primaryKey(),author:text('author').notNull(),lat:integer('lat').notNull(),lon:integer('lon').notNull(),city:text('city').notNull(),country:text('country'),level:integer('level').notNull(),kind:text('kind').notNull(),options:text('options').notNull().default('[]'),photo:text('photo'),created:integer('created').notNull(),expires:integer('expires').notNull(),hidden:integer('hidden').notNull().default(0),deleted:integer('deleted').notNull().default(0)},t=>[index('sky_active').on(t.expires,t.created),index('sky_author').on(t.author,t.created),index('sky_area').on(t.lat,t.lon)]);
export const skyBlocks=sqliteTable('sky_blocks',{actor:text('actor').notNull(),target:text('target').notNull()},t=>[primaryKey({columns:[t.actor,t.target]})]);
export const skyFlags=sqliteTable('sky_flags',{actor:text('actor').notNull(),report:text('report').notNull(),reason:text('reason').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.actor,t.report]})]);
export const skyEvidence=sqliteTable('sky_evidence',{report:text('report').notNull(),witness:text('witness').notNull(),author:text('author').notNull(),agrees:integer('agrees').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.report,t.witness]}),index('sky_evidence_author').on(t.author)]);

export const dpcBulletins=sqliteTable('dpc_bulletins',{day:text('day').primaryKey(),snapshot:text('snapshot').notNull(),issued:text('issued').notNull(),source:text('source').notNull(),checked:integer('checked').notNull(),attempted:integer('attempted').notNull(),failed:integer('failed').notNull().default(0)});
export const dpcZones=sqliteTable('dpc_zones',{snapshot:text('snapshot').notNull(),slot:integer('slot').notNull(),geometry:text('geometry').notNull()},t=>[primaryKey({columns:[t.snapshot,t.slot]})]);

export const skyConfirmations=sqliteTable('sky_confirmations',{report:text('report').notNull(),device:text('device').notNull(),actor:text('actor').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.report,t.device]}),uniqueIndex('sky_confirm_actor').on(t.report,t.actor)]);

export const moderationSessions=sqliteTable('moderation_sessions',{token:text('token').primaryKey(),credential:text('credential').notNull(),expires:integer('expires').notNull()});
export const moderationBans=sqliteTable('moderation_bans',{key:text('key').primaryKey(),created:integer('created').notNull()});
export const actorDevices=sqliteTable('actor_devices',{actor:text('actor').notNull(),device:text('device').notNull()},t=>[primaryKey({columns:[t.actor,t.device]})]);

// School questions: short-lived, fixed answers; no public identity or exact location.
export const zoneQuestions=sqliteTable('zone_questions',{topic:text('topic').notNull().default('school'),id:text('id').primaryKey(),author:text('author').notNull(),city:text('city').notNull(),lat:integer('lat').notNull(),lon:integer('lon').notNull(),day:text('day').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull(),deleted:integer('deleted').notNull().default(0)},t=>[index('questions_active').on(t.expires),index('questions_author').on(t.author,t.created)]);
export const zoneAnswers=sqliteTable('zone_answers',{id:text('id').primaryKey(),question:text('question').notNull(),author:text('author').notNull(),answer:text('answer').notNull(),url:text('url').notNull().default(''),created:integer('created').notNull(),hidden:integer('hidden').notNull().default(0),deleted:integer('deleted').notNull().default(0)},t=>[uniqueIndex('answer_per_person').on(t.question,t.author),index('answers_question').on(t.question,t.created)]);
export const zonePresence=sqliteTable('zone_presence',{actor:text('actor').primaryKey(),lat:integer('lat').notNull(),lon:integer('lon').notNull(),created:integer('created').notNull()});
export const questionLimits=sqliteTable('question_limits',{actor:text('actor').primaryKey(),last:integer('last').notNull()});
export const answerNotices=sqliteTable('answer_notices',{id:text('id').primaryKey(),actor:text('actor').notNull(),question:text('question').notNull(),created:integer('created').notNull(),seen:integer('seen').notNull().default(0),pushed:integer('pushed').notNull().default(0)},t=>[uniqueIndex('notice_first_answer').on(t.question),index('notice_actor').on(t.actor,t.created)]);
export const answerSubscriptions=sqliteTable('answer_subscriptions',{device:text('device').primaryKey(),actor:text('actor').notNull(),endpoint:text('endpoint').notNull(),created:integer('created').notNull()},t=>[index('subscription_actor').on(t.actor)]);
export const answerPushPrefs=sqliteTable('answer_push_prefs',{actor:text('actor').primaryKey(),enabled:integer('enabled').notNull().default(0),later:integer('later').notNull().default(0)});

export const globeSnapshots=sqliteTable('globe_snapshots',{name:text('name').primaryKey(),payload:text('payload').notNull().default(''),updated:integer('updated').notNull().default(0),attempted:integer('attempted').notNull().default(0),lease:integer('lease').notNull().default(0)});

export const feedbackPushPrefs=sqliteTable('feedback_push_prefs',{actor:text('actor').primaryKey(),enabled:integer('enabled').notNull().default(0)});
export const feedbackNotices=sqliteTable('feedback_notices',{id:text('id').primaryKey(),actor:text('actor').notNull(),report:text('report').notNull(),created:integer('created').notNull(),pushed:integer('pushed').notNull().default(0)},t=>[uniqueIndex('feedback_report').on(t.report),index('feedback_actor').on(t.actor,t.created)]);

export const publicZones=sqliteTable('public_zones',{slug:text('slug').primaryKey(),name:text('name').notNull(),lat:integer('lat').notNull(),lon:integer('lon').notNull(),created:integer('created').notNull()});
export const morningForecasts=sqliteTable('morning_forecasts',{zone:text('zone').notNull(),day:text('day').notNull(),captured:integer('captured').notNull(),payload:text('payload').notNull()},t=>[primaryKey({columns:[t.zone,t.day]})]);
export const eventGroups=sqliteTable('event_groups',{id:text('id').primaryKey(),name:text('name').notNull(),city:text('city').notNull(),lat:integer('lat').notNull(),lon:integer('lon').notNull(),day:text('day').notNull(),creator:text('creator').notNull(),token:text('token').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull(),baseline:text('baseline').notNull().default(''),changed:integer('changed').notNull().default(0)});
export const eventMembers=sqliteTable('event_members',{group:text('group').notNull(),actor:text('actor').notNull()},t=>[primaryKey({columns:[t.group,t.actor]})]);
export const humanVotes=sqliteTable('human_votes',{actor:text('actor').primaryKey(),lat:integer('lat').notNull(),lon:integer('lon').notNull(),cold:integer('cold').notNull(),created:integer('created').notNull()});

export const eventPushPrefs=sqliteTable('event_push_prefs',{actor:text('actor').primaryKey(),enabled:integer('enabled').notNull().default(0)});
export const eventNotices=sqliteTable('event_notices',{id:text('id').primaryKey(),actor:text('actor').notNull(),event:text('event').notNull(),created:integer('created').notNull(),seen:integer('seen').notNull().default(0),pushed:integer('pushed').notNull().default(0)},t=>[uniqueIndex('event_notice_once').on(t.event,t.actor),index('event_notice_actor').on(t.actor,t.seen)]);

// Immutable copies acquired from the weather provider, with no user/device identity.
export const forecastCopies=sqliteTable('forecast_copies',{id:text('id').primaryKey(),location:text('location').notNull(),slot:integer('slot').notNull(),captured:integer('captured').notNull(),timezone:text('timezone').notNull(),previousId:text('previous_id'),changed:integer('changed').notNull(),changes:text('changes').notNull(),payload:text('payload').notNull(),hash:text('hash').notNull()},t=>[uniqueIndex('forecast_copies_location_slot').on(t.location,t.slot),index('forecast_copies_location_captured').on(t.location,t.captured)]);

// Daily community question: shared per approximate zone; one answer per browser/day.
export const dailyQuestions=sqliteTable('daily_questions',{id:text('id').primaryKey(),zone:text('zone').notNull(),day:text('day').notNull(),topic:text('topic').notNull(),timezone:text('timezone').notNull(),opens:integer('opens').notNull(),expires:integer('expires').notNull(),created:integer('created').notNull()},t=>[uniqueIndex('daily_question_zone_day').on(t.zone,t.day),index('daily_question_expiry').on(t.expires)]);
export const dailyAnswers=sqliteTable('daily_answers',{device:text('device').notNull(),day:text('day').notNull(),question:text('question').notNull(),actor:text('actor').notNull(),answer:text('answer').notNull(),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.device,t.day]}),index('daily_answer_question').on(t.question),index('daily_answer_day').on(t.day)]);

export const actorProfessions=sqliteTable('actor_professions',{actor:text('actor').primaryKey(),mestiere:text('mestiere').notNull(),updated:integer('updated').notNull()});
