import assert from 'node:assert/strict';
import {normalizeRainbowWeather,fetchRainbowWeather} from '../server/rainbow-client.mjs';
const now=Date.parse('2026-09-23T12:30:00Z'),at=Date.parse('2026-09-23T12:00:00Z')/1000;
const raw={generatedAtTimestamp:at,location:{lat:41.9,lon:12.5},units:{temperature:'celsius',feelsLikeTemperature:'celsius',windSpeed:'meter_per_second',windGust:'meter_per_second',humidity:'percent',precipitationChance:'percent'},timelines:{hourly:[{startTimestamp:at,temperature:0,feelsLikeTemperature:-2,windSpeed:10,windGust:15,humidity:65,precipitationChance:0,condition:'Clear'},{startTimestamp:at+3600,temperature:1,condition:'Cloudy'}]}};
const data=normalizeRainbowWeather(raw,now);
assert.equal(data.forThisHour.temperature,0);
assert.equal(data.forThisHour.feelsLike,-2);
assert.equal(data.forThisHour.windKmh,36);
assert.equal(data.forThisHour.gustKmh,54);
assert.equal(data.forThisHour.precipitationProbability,0);
assert.equal(data.forThisHour.pressureHpa,null);
assert.equal(data.kind,'forecast');
assert.equal(data.issuedAt,at*1000);
assert.equal(normalizeRainbowWeather({...raw,generatedAtTimestamp:at-3600},now-3600000).forThisHour,null);
assert.equal(normalizeRainbowWeather(raw,now+10800000).stale,true);
assert.equal(normalizeRainbowWeather(raw,now+10800000).forThisHour,null);
assert.throws(()=>normalizeRainbowWeather({...raw,units:{...raw.units,temperature:'fahrenheit'}},now),/Unità/);
assert.throws(()=>normalizeRainbowWeather({...raw,generatedAtTimestamp:at+7200},now),/Orario/);
assert.throws(()=>normalizeRainbowWeather({...raw,timelines:{hourly:[raw.timelines.hourly[0],raw.timelines.hourly[0]]}},now),/Orario/);
let calls=0,reserved=false;
const options={key:'fixture-not-a-real-key',latitude:41.9,longitude:12.5,now,beforeRequest:async()=>{reserved=true},fetcher:async(url,init)=>{
 calls++;assert.equal(reserved,true);assert.equal(new URL(url).pathname,'/weather/v1/forecast/12.5/41.9');assert.equal(new URL(url).searchParams.has('token'),false);assert.equal(init.headers['Ocp-Apim-Subscription-Key'],'fixture-not-a-real-key');assert.equal(init.redirect,'manual');return new Response(JSON.stringify(raw));
}};
assert.equal((await fetchRainbowWeather(options)).forThisHour.temperature,0);
assert.equal(calls,1);
await assert.rejects(fetchRainbowWeather({...options,beforeRequest:undefined}),/Protezione/);
await assert.rejects(fetchRainbowWeather({...options,beforeRequest:async()=>{throw Error('Quota raggiunta')}}),/Quota/);
assert.equal(calls,1);
await assert.rejects(fetchRainbowWeather({...options,fetcher:async()=>new Response('private upstream text',{status:401})}),/^Error: Rainbow Weather temporaneamente non disponibile$/);
await assert.rejects(fetchRainbowWeather({...options,fetcher:async()=>new Response(JSON.stringify({...raw,location:{lat:35,lon:139}}))}),/Località/);
await assert.rejects(fetchRainbowWeather({...options,latitude:NaN}),/Coordinate/);
console.log('Rainbow client: unit conversion, UTC validity, source, quota guard and sanitized failures passed.');
